#!/bin/sh
# SPDX-License-Identifier: GPL-2.0
# Generate DEFINE_CRYPTO_FN_REDIRECT() calls for all exported symbols
#
# Usage: gen-fips140-fn-redirect.sh <.fips140.exported> <output.h>

EXPORTED="$1"
OUTPUT="$2"

if [ ! -f "$EXPORTED" ]; then
	echo "/* exported symbol list not found, empty redirect list */" > "$OUTPUT"
	exit 0
fi

TMPFILE="${OUTPUT}.tmp"

{
	echo "/* SPDX-License-Identifier: GPL-2.0 */"
	echo "/* Auto-generated by gen-fips140-fn-redirect.sh — do not edit */"
	echo ""
	awk '{print "DEFINE_CRYPTO_FN_REDIRECT(" $2 ")"}' "$EXPORTED"
} > "$TMPFILE"

if [ -f "$OUTPUT" ] && cmp -s "$TMPFILE" "$OUTPUT"; then
	rm -f "$TMPFILE"
else
	mv "$TMPFILE" "$OUTPUT"
fi
