# SPDX-License-Identifier: GPL-2.0
crypto-objs-$(CONFIG_ASYNC_CORE) += async_tx.o
crypto-objs-$(CONFIG_ASYNC_MEMCPY) += async_memcpy.o
crypto-objs-$(CONFIG_ASYNC_XOR) += async_xor.o
crypto-objs-$(CONFIG_ASYNC_PQ) += async_pq.o
crypto-objs-$(CONFIG_ASYNC_RAID6_RECOV) += async_raid6_recov.o
obj-$(CONFIG_ASYNC_RAID6_TEST) += raid6test.o
