#ifndef _ENA_CONFIG_H_
#define _ENA_CONFIG_H_
#define ENA_HAVE_PCI_DEV_ID 1
#define ENA_HAVE_XDP_DO_FLUSH 1
#define ENA_HAVE_CPUMASK_LOCAL_SPREAD 1
#define ENA_HAVE_UPDATE_AFFINITY_HINT 1
#define ENA_HAVE_ETHTOOL_PUTS 1
#define ENA_HAVE_ETHTOOL_RXFH_PARAM 1
#define ENA_HAVE_ETHTOOL_OPS_SUPPORTED_COALESCE_PARAMS 1
#define ENA_HAVE_ETH_HW_ADDR_SET 1
#define ENA_XSK_BUFF_DMA_SYNC_SINGLE_ARG 1
#define ENA_HAVE_NETDEV_XDP_ACT_XSK_ZEROCOPY 1
#define ENA_ETHTOOL_NFC_IPV6_SUPPORTED 1
#define ENA_HAVE_KERNEL_ETHTOOL_TS_INFO 1
#define ENA_HAVE_XDP_FEATURES_SET_REDIRECT_TARGET 1
#define ENA_HAVE_XDP_SET_FEATURES_FLAG 1
#define ENA_HAVE_NETDEV_XDP_FEATURES 1
#define ENA_PHC_SUPPORT_ADJFINE 1
#define ENA_NAPI_IRQ_AND_QUEUE_ASSOC 1
#endif /* _ENA_CONFIG_H_ */
