#ifndef _ENA_CONFIG_H_
#define _ENA_CONFIG_H_
#define ENA_HAVE_PCI_DEV_ID 1
#define ENA_HAVE_XDP_DO_FLUSH 1
#define ENA_HAVE_CPUMASK_LOCAL_SPREAD 1
#define ENA_HAVE_UPDATE_AFFINITY_HINT 1
#define ENA_HAVE_ETHTOOL_PUTS 1
#define ENA_HAVE_ETHTOOL_RXFH_PARAM 1
#define ENA_HAVE_ETHTOOL_OPS_SUPPORTED_COALESCE_PARAMS 1
#define ENA_HAVE_ETH_HW_ADDR_SET 1
#define ENA_XSK_BUFF_DMA_SYNC_SINGLE_ARG 1
#define ENA_ETHTOOL_NFC_IPV6_SUPPORTED 1
#define ENA_HAVE_KERNEL_ETHTOOL_TS_INFO 1
#define ENA_HAVE_NETDEV_XDP_FEATURES 1
#ifdef ENA_PHC_INCLUDE
#define ENA_PHC_SUPPORT 1
#endif
#define ENA_PHC_SUPPORT_ADJFINE 1
#define ENA_NAPI_IRQ_AND_QUEUE_ASSOC 1
#define ENA_HAVE_SKB_FRAG_FILL_PAGE_DESC 1
#define ENA_HAVE_XDP_MB_DEPS 1
#define ENA_HAVE_SKB_METADATA_SET 1
#define ENA_HAVE_DEL_TIMER 1
#define ENA_HAVE_ATOMIC_SET_RELEASE 1
#define ENA_HAVE_SMP_STORE_RELEASE 1
#define ENA_HAVE_NDO_ETH_IOCTL 1
#define ENA_HAVE_NDO_HWTSTAMP 1
#define ENA_HAVE_HWTSTAMP_FILTER_NTP_ALL 1
#define ENA_HAVE_NETDEV_QUEUE_STATS 1
#define ENA_HAS_DEVLINK_HEADERS 1
#define ENA_HAVE_XDP_HINTS_DEPS 1
#define ENA_HAVE_XSK_POOL_FILL_CB 1
#define ENA_HAVE_XSK_TX_METADATA 1
#define ENA_HAVE_NAPI_STATE_BUSY_POLL 1
#define ENA_HAVE_TXQ_TRANS_UPDATE 1
#endif /* _ENA_CONFIG_H_ */
