obj-$(CONFIG_LUSTRE_FS) += fid/
obj-$(CONFIG_LUSTRE_FS) += obdclass/
obj-$(CONFIG_LUSTRE_FS) += ptlrpc/
obj-$(CONFIG_LUSTRE_FS) += obdecho/
obj-$(CONFIG_LUSTRE_FS) += mgc/
obj-$(CONFIG_LUSTRE_FS) += lov/ osc/ mdc/ lmv/ llite/ fld/

include $(srctree)/fs/lustre/Makefile.rules
